[package]
name = "slicer-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "slicer"
path = "src/main.rs"

[dependencies]
slicer-core = { path = "../slicer-core" }
slicer-passes = { path = "../slicer-passes" }
slicer-validator = { path = "../slicer-validator" }

clap = { workspace = true }
anyhow = { workspace = true }
